# Generated by Django 2.0 on 2018-01-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_image_field_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_field_team',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='image_field_team',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='image_field_team',
            name='Image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
