# Generated by Django 2.0 on 2018-01-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20180130_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_field_team',
            name='post',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
