# Generated by Django 2.0 on 2018-01-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_image_field_team_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('Img', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, upload_to='')),
                ('heading', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='image_field_team',
            name='fb_link',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='image_field_team',
            name='git_link',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='image_field_team',
            name='linkedin_link',
            field=models.URLField(max_length=50),
        ),
    ]
