# Generated by Django 2.0 on 2018-01-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20180130_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='text',
        ),
    ]
