# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_auto_20180205_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
