# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-06 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_auto_20180206_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
