# Generated by Django 2.0 on 2018-02-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_auto_20180207_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
