# Generated by Django 2.0 on 2018-02-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_our_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('1st', 'Technical'), ('2nd', 'Event-Management'), ('3rd', 'Creativity'), ('4th', 'Publicity')], default='Publicity', max_length=50)),
            ],
        ),
    ]
