# Generated by Django 2.0 on 2018-02-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_team_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='team_details',
            new_name='Team',
        ),
    ]
