# Generated by Django 2.0 on 2018-02-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_auto_20180207_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.CharField(choices=[('1st', 'Technical'), ('2nd', 'Event-Management'), ('3rd', 'Creativity'), ('4th', 'Publicity')], default='4th', max_length=50),
        ),
    ]
