# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0021_auto_20180207_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
