# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0022_about_us_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us_content',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
