# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0023_about_us_content_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(choices=[('1st', 'GENERAL SECRETARY'), ('2nd', 'JOINT SECRETARY')], default='2nd', max_length=50)),
                ('Image', models.FileField(blank=True, upload_to='')),
                ('fb_link', models.URLField(max_length=50)),
                ('git_link', models.URLField(max_length=50)),
                ('linkedin_link', models.URLField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Image_Field_Team',
        ),
    ]
