# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0024_auto_20180208_0405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Secretaries',
            new_name='Secretarie',
        ),
    ]
