# Generated by Django 2.0 on 2018-02-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0026_auto_20180208_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
