# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0028_auto_20180209_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspirus_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.FileField(upload_to='')),
                ('register_link', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MSWeek_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.FileField(upload_to='')),
                ('register_link', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rumble_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.FileField(upload_to='')),
                ('register_link', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
