# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0029_inspirus_event_msweek_event_rumble_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('msweek', 'MS Week'), ('inspirus', 'Inspirus'), ('rumble', 'Rumble')], default='msweek', max_length=50),
        ),
    ]
